In [123]:
import numpy as np
#numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0) 
arr = np.array([1,2,3,4])

print(arr)
print(arr*2)
print(type(arr))

a = np.array([1, 2, 3,4,5], ndmin = 3)  
print(a) 

#data type 

array=np.array([1,2,3,4] ,dtype=np.int8) # int16,int32,int 64
array2=np.array([1.2,3.3], dtype=np.float64)
array3=np.array([1,2,3,0] ,dtype=np.bool_)
array4=np.array([1,2,3,4] ,dtype=np.str_)
array5=np.array(['Ned','Rob','Snow','Bob'] ,dtype="<U2")
array6=np.array([1,2.2,'ned',4,True] ,dtype=np.object_)
array7 = array.astype(np.str_)
print(f"type-{array.dtype}, uses-{array.nbytes} bytes")
print(f"type-{array2.dtype}, uses-{array2.nbytes} bytes")
print(f"{array3} type-{array3.dtype}, uses-{array3.nbytes} bytes")
print(f"{array4} type-{array4.dtype}, uses-{array4.nbytes} bytes")
print(f"{array5} type-{array5.dtype}, uses-{array5.nbytes} bytes")
print(f"{array6} type-{array6.dtype}, uses-{array6.nbytes} bytes")
print(f"{array7} type-{array7.dtype}, uses-{array7.nbytes} bytes")

[1 2 3 4]
[2 4 6 8]
<class 'numpy.ndarray'>
[[[1 2 3 4 5]]]
type-int8, uses-4 bytes
type-float64, uses-16 bytes
[ True  True  True False] type-bool, uses-4 bytes
['1' '2' '3' '4'] type-<U1, uses-16 bytes
['Ne' 'Ro' 'Sn' 'Bo'] type-<U2, uses-32 bytes
[1 2.2 'ned' 4 True] type-object, uses-40 bytes
['1' '2' '3' '4'] type-<U4, uses-64 bytes


In [16]:
import numpy as np

arr= np.array([ [ ['a','b'],['c','d'] ],
                [ ['e','f'],['g',''] ]  ])
print(arr.ndim)
print(arr.shape)
print(arr[1,1,0])

word=arr[0,0,0] + arr[1,1,0] + arr[1,0,0]
print(word)

3
(2, 2, 2)
g
age


In [40]:
import numpy as np

arr= np.array([ [1,2,3],
               [4,5,6],
               [7,8,9] ])

# sliceing array[start:end:step]  end is exclusive  , step- 1-next,2-ekchodke

print(arr[0::2])
print(arr[::-2])

# slicing coloum array[::: , start:end:step]

print(arr[:,0::2])

#8,,2
print(arr[::-2 , 1])

#9,7 | 3,1
print(arr[2::-2, 2::-2])

[[1 2 3]
 [7 8 9]]
[[7 8 9]
 [1 2 3]]
[[1 3]
 [4 6]
 [7 9]]
[8 2]
[[9 7]
 [3 1]]


In [55]:
import numpy as np

arr= np.array( [1,2,3] )

print(arr +2)
print(arr * 2)
print(arr ** 3)

print(np.sqrt(arr))
print(np.round(np.sqrt(arr)))  # round down .floor() round up .ceil()

# if we have to find area of circle 
print(np.pi * arr**2)    # pi*r^2

arr2=np.array([4,5,6])

print(arr + arr2)
print(arr / arr2)

# compaison 
arr3=np.array([95,90,92,100,75])
print(arr3==100)
print(arr3>80)
arr3[arr3<80]=0
print(arr3)

[3 4 5]
[2 4 6]
[ 1  8 27]
[1.         1.41421356 1.73205081]
[1. 1. 2.]
[ 3.14159265 12.56637061 28.27433388]
[5 7 9]
[0.25 0.4  0.5 ]
[False False False  True False]
[ True  True  True  True False]
[ 95  90  92 100   0]


In [59]:
import numpy as np
#broadcasting 
arr1=np.array([[1,2,3,4]])
arr2=np.array([[1],[2],[3],[4]])
arr3=np.array([[1,2],[2,3],[3,4],[4,5]])
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr1*arr2)
print(arr2*arr3)

(1, 4)
(4, 1)
(4, 2)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
[[ 1  2]
 [ 4  6]
 [ 9 12]
 [16 20]]


In [109]:
import numpy as np

arr=np.zeros((2,5)) #(shape)
arr2=np.ones((2,5))
arr3=np.full((2,5),3)
arr4=np.eye(3) # for identity
arr5=np.empty((2,4))
arr6=np.arange(0,11,.5) #start, stop, steps
arr6=np.linspace(0,11,4) #start, stop, num-pints we want 
print(arr,arr2,arr3,arr4,arr5,arr6)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] [[3 3 3 3 3]
 [3 3 3 3 3]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [[4.9e-324 9.9e-324 9.9e-324 1.5e-323]
 [1.5e-323 2.0e-323 2.0e-323 2.5e-323]] [ 0.          3.66666667  7.33333333 11.        ]


In [62]:
import numpy as np 
# aggrigation
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10]])

print(np.sum(arr))
print(np.mean(arr))
print(np.var(arr))
print(np.std(arr))
print(np.min(arr))
print(np.argmin(arr))
print(np.max(arr))
print(np.argmax(arr))

print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

55
5.5
8.25
2.8722813232690143
1
0
10
9
[ 7  9 11 13 15]
[15 40]


In [68]:
import numpy as np
# filtring
age=np.array([[21,22,19,39,37],
              [17,21,23,18,22]])

teen=age[age<19]
regularSt = age[(age>19) & (age<25)]  # &-and , | - or
print(teen)
print(regularSt)

adults= np.where(age>=18,age, 0)
print(adults)

[17 18]
[21 22 21 23 22]
[[21 22 19 39 37]
 [ 0 21 23 18 22]]


In [95]:
import numpy as np
# random
rnge= np.random.default_rng()
print(rnge.integers(0,101,size=(3,2))) #101 in excusive 

print(np.random.uniform(low=-1,high=1,size=3))

arr=np.array([1,2,3,4,5])
rnge.shuffle(arr)
print(arr)

names=np.array(['Ned','Rob','Snow','Bob'])
name=rnge.choice(names,size=2)
print(name)

[[75 60]
 [ 9 94]
 [ 3 13]]
[-0.63459561 -0.63491843  0.58762896]
[3 4 1 5 2]
['Ned' 'Ned']
